apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-kgrf
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci10t-786-0088-tenant/ci10t-786-0088-app/devfile-sample-kgrf@sha256:98bb76c455f59257a9b13e88683378e387077b542e1264cc82dd891f947eff56
        name: my-nodejs
        resources: {}
status: {}
